name: Monthly WebHostMost Login

on:
  workflow_dispatch: # 允许手动触发
  schedule:
    # 每个月1号的午夜 (UTC 时间) 运行
    # Cron 语法: 分 时 日 月 周
    # '0 0 1 * *' 表示: 0分钟，0小时，每月的1号，每个月，每周的每一天
    - cron: '0 0 1 * *'

jobs:
  login_and_check:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu Runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 拉取你的代码

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # 或者你希望使用的 Python 版本

      - name: Install Chrome Browser
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # webdriver-manager 会在这里被调用来下载 ChromeDriver

      - name: Run login script
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }} # 从 GitHub Secrets 读取账号信息
        run: python login.py