name: 每月自动登录任务
on:
  schedule:
    # 每月10日 6:36 北京时间（UTC+8），对应UTC时间为每月9日22:36
    - cron: '36 22 9 * *'
  workflow_dispatch:  # 支持手动触发测试

jobs:
  login-job:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: 安装Chrome浏览器
        run: |
          sudo apt-get update -y
          sudo apt-get install -y google-chrome-stable

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: 运行登录脚本
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}  # 从仓库Secrets获取账号信息
        run: python login.py
        continue-on-error: true  # 允许任务继续执行以生成调试文件

      - name: 上传调试文件（失败时）
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: login-debug-files
          path: |
            debug_*.png
            debug_*.html
          retention-days: 7
