name: Monthly WebHostMost Login (Every ~21 Days, Randomized Hour)

on:
  workflow_dispatch: # Allows manual triggering for testing
  schedule:
    # Runs at 06:00 UTC on the 1st and 22nd day of every month.
    # This provides an approximate 21-day interval.
    # The Python script will then add a random delay up to 59 minutes.
    - cron: '0 6 1 * *'
    - cron: '0 6 22 * *'

jobs:
  login_and_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install Google Chrome Stable
        run: |
          sudo apt-get update -y
          sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run login script
        id: login_script
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        run: python login.py
        continue-on-error: true # Keep true to allow artifact upload even on script failure

      - name: Upload debug artifacts if login script had issues
        if: steps.login_script.outcome != 'success'
        uses: actions/upload-artifact@v4
        with:
          name: login-debug-artifacts-${{ github.run_id }}
          path: |
            *.png
            *.html
          retention-days: 7

      - name: Check script execution outcome and fail job if needed
        if: steps.login_script.outcome != 'success' # Or steps.login_script.conclusion == 'failure'
        run: |
          echo "Login script finished with an unsuccessful outcome (see logs and artifacts)."
          # If you want the ENTIRE GITHUB ACTION JOB to fail if the python script indicates failure
          # (e.g. by overall_success_count != len(accounts) or by python script exit(1))
          # then you MUST ensure the python script exits with a non-zero code for errors
          # AND this step uses that to fail the job.
          # The current python script does not exit(1) in main() by default but can be enabled.
          # For now, this step just logs. To make it fail the job:
          echo "At least one account failed or a critical error occurred. Marking job as failed."
          exit 1
