name: Monthly WebHostMost Login

on:
  workflow_dispatch: # Allows manual triggering for testing
  schedule:
    # Runs at 06:35 UTC on the 10th day of every month.
    - cron: '35 6 10 * *'

jobs:
  login_and_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Google Chrome Stable
        run: |
          sudo apt-get update -y
          sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run login script
        id: login_script
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        run: python login.py
        continue-on-error: false # Set to false to fail the job immediately if the script fails

      - name: Upload debug artifacts if login script had issues
        if: steps.login_script.outcome != 'success'
        uses: actions/upload-artifact@v4
        with:
          name: login-debug-artifacts-${{ github.run_id }}
          path: |
            *.png
            *.html
          retention-days: 7

      - name: Send notification if login script failed
        if: steps.login_script.outcome != 'success'
        run: |
          # Replace this with actual notification code, e.g., sending an email or a Slack message
          echo "Login script failed. Please check the artifacts and logs."
